services:
  logbook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    networks:
      - internal
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - logbook_data:/app/data

  caddy:
    image: caddybuilds/caddy-cloudflare:2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    networks:
      - internal

networks:
  internal:
    
volumes:
  caddy_data:
  caddy_config:
  logbook_data: